version: "3.6"

services: 
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
        environment: 
              - node.name=es01
              - cluster.name=docker-cluster
              - cluster.initial_master_nodes=es01
        ports:
            - "9200:9200"
    logstash:
        image: docker.elastic.co/logstash/logstash:7.6.2
        volumes: 
            - ./.docker/logstash/conf.d/:/usr/share/logstash/pipeline/
            - ./coronavirus/data//:/usr/share/logstash/user_data/
        depends_on: 
            - elasticsearch
        command: /usr/share/logstash/bin/logstash -f /usr/share/logstash/pipeline/file.conf
    kibana:
        image: docker.elastic.co/kibana/kibana:7.6.2
        depends_on: 
            - elasticsearch
        ports: 
            - "5601:5601"
